tap "hashicorp/tap"
tap "homebrew/bundle"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "teamookla/speedtest"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Bash, Zsh and Fish completion for Docker
brew "docker-completion"
# GNU compiler collection
brew "gcc"
# Distributed revision control system
brew "git"
# Interpreted, interactive, object-oriented programming language
brew "python@3.12"
# Quickly rewrite git repository history
brew "git-filter-repo"
# Validating, recursive, caching DNS resolver
brew "unbound"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Modern load testing tool, using Go and JavaScript
brew "k6"
# Command-line tool to kill processes listening on a specific port
brew "killport"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool that can switch between kubectl contexts easily and create aliases
brew "kubectx"
# Clone of ls with colorful output, file type icons, and more
brew "lsd"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Development kit for the Java programming language
brew "openjdk@17"
# 7-Zip (high compression file archiver) implementation
brew "p7zip"
# Prints a steam locomotive if you type sl instead of ls
brew "sl"
# Cross-shell prompt for astronauts
brew "starship"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Executes a program periodically, showing output fullscreen
brew "watch"
# Utilities to create and convert Web Open Font File (WOFF) files
brew "woff2"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Pluggable terminal workspace, with terminal multiplexer as the base feature
brew "zellij"
# Vault
brew "hashicorp/tap/vault"
# Ookla Speedtest
brew "teamookla/speedtest/speedtest"
# Enable Windows-like alt-tab
cask "alt-tab"
# Eclipse-based LDAP browser and directory client
cask "apache-directory-studio"
# Voice and text chat software
cask "discord"
cask "font-fira-code-nerd-font"
cask "font-monaspace"
# GIT client
cask "fork"
# Java IDE by JetBrains
cask "intellij-idea"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar manager
cask "jordanbaird-ice"
# Open-source keystroke visualiser
cask "keycastr"
# Clipboard manager
cask "maccy"
# Calculator and converter application
cask "numi"
# Replacement for Docker Desktop
cask "orbstack"
# Collaboration platform for API development
cask "postman"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# Screenshot measurement and annotation tool
cask "shottr"
# Unpacks archive files
cask "the-unarchiver"
# Tool to invert scroll direction for physical scroll wheels
cask "unnaturalscrollwheels"
# Code editor
cask "visual-studio-code-insiders"
